// src/components/Sidebar.vue
<script setup lang="ts">
import { useScenarioStore } from '../store/scenario'
import type { ScenarioElementType } from '../types/scenario'

const store = useScenarioStore()

const tabs: { key: ScenarioElementType | 'overview'; label: string }[] = [
  { key: 'overview', label: '概要' },
  { key: 'scene', label: 'シーン' },
  { key: 'npc', label: 'NPC' },
  { key: 'location', label: '場所' },
  { key: 'clue', label: '手がかり' },
  { key: 'event', label: 'イベント' },
]

function getItems(tab: ScenarioElementType) {
  switch (tab) {
    case 'npc': return store.scenario.npcs
    case 'location': return store.scenario.locations
    case 'clue': return store.scenario.clues
    case 'event': return store.scenario.events
    case 'scene': return store.scenario.scenes
  }
}

function handleAdd() {
  if (store.activeTab === 'overview') return
  const actionMap: Record<ScenarioElementType, () => void> = {
    npc: () => store.addNpc(),
    location: () => store.addLocation(),
    clue: () => store.addClue(),
    event: () => store.addEvent(),
    scene: () => store.addScene(),
  }
  actionMap[store.activeTab]()
}
</script>

<template>
  <aside class="sidebar">
    <div class="sidebar-header">
      <h2>{{ store.scenario.title }}</h2>
      <span v-if="store.isDirty" class="dirty-indicator">未保存</span>
    </div>

    <nav class="sidebar-tabs">
      <button
        v-for="tab in tabs"
        :key="tab.key"
        :class="['tab-btn', { active: store.activeTab === tab.key }]"
        @click="store.setActiveTab(tab.key)"
      >
        {{ tab.label }}
      </button>
    </nav>

    <div v-if="store.activeTab !== 'overview'" class="sidebar-list">
      <button class="add-btn" @click="handleAdd">
        + 追加
      </button>
      <ul>
        <li
          v-for="item in getItems(store.activeTab as ScenarioElementType)"
          :key="item.id"
          :class="{ selected: store.selectedElement?.id === item.id }"
          @click="store.selectElement({ type: store.activeTab as ScenarioElementType, id: item.id })"
        >
          {{ item.name }}
        </li>
      </ul>
    </div>
  </aside>
</template>

// src/components/Sidebar.tsx
import { useScenario } from '../store/ScenarioContext';
import type { ScenarioElementType } from '../types/scenario';

const tabs: { key: ScenarioElementType | 'overview'; label: string }[] = [
  { key: 'overview', label: '概要' },
  { key: 'scene', label: 'シーン' },
  { key: 'npc', label: 'NPC' },
  { key: 'location', label: '場所' },
  { key: 'clue', label: '手がかり' },
  { key: 'event', label: 'イベント' },
];

export function Sidebar() {
  const { state, dispatch } = useScenario();
  const { scenario, activeTab, selectedElement } = state;

  const getItems = (tab: ScenarioElementType) => {
    switch (tab) {
      case 'npc': return scenario.npcs;
      case 'location': return scenario.locations;
      case 'clue': return scenario.clues;
      case 'event': return scenario.events;
      case 'scene': return scenario.scenes;
    }
  };

  const handleAdd = () => {
    if (activeTab === 'overview') return;
    const actionMap: Record<ScenarioElementType, string> = {
      npc: 'ADD_NPC',
      location: 'ADD_LOCATION',
      clue: 'ADD_CLUE',
      event: 'ADD_EVENT',
      scene: 'ADD_SCENE',
    };
    dispatch({ type: actionMap[activeTab] as never });
  };

  return (
    <aside className="sidebar">
      <div className="sidebar-header">
        <h2>{scenario.title}</h2>
        {state.isDirty && <span className="dirty-indicator">未保存</span>}
      </div>

      <nav className="sidebar-tabs">
        {tabs.map((tab) => (
          <button
            key={tab.key}
            className={`tab-btn ${activeTab === tab.key ? 'active' : ''}`}
            onClick={() => dispatch({ type: 'SET_ACTIVE_TAB', payload: tab.key })}
          >
            {tab.label}
          </button>
        ))}
      </nav>

      {activeTab !== 'overview' && (
        <div className="sidebar-list">
          <button className="add-btn" onClick={handleAdd}>
            + 追加
          </button>
          <ul>
            {getItems(activeTab)?.map((item) => (
              <li
                key={item.id}
                className={selectedElement?.id === item.id ? 'selected' : ''}
                onClick={() => dispatch({ type: 'SELECT_ELEMENT', payload: { type: activeTab, id: item.id } })}
              >
                {item.name}
              </li>
            ))}
          </ul>
        </div>
      )}
    </aside>
  );
}
