// src/App.tsx
import { ScenarioProvider, useScenario } from './store/ScenarioContext';
import { Sidebar } from './components/Sidebar';
import { OverviewEditor } from './components/OverviewEditor';
import { NPCEditor } from './components/NPCEditor';
import { LocationEditor } from './components/LocationEditor';
import { ClueEditor } from './components/ClueEditor';
import { EventEditor } from './components/EventEditor';
import { SceneEditor } from './components/SceneEditor';
import './App.css';

function EditorContent() {
  const { state } = useScenario();

  const renderEditor = () => {
    switch (state.activeTab) {
      case 'overview': return <OverviewEditor />;
      case 'npc': return <NPCEditor />;
      case 'location': return <LocationEditor />;
      case 'clue': return <ClueEditor />;
      case 'event': return <EventEditor />;
      case 'scene': return <SceneEditor />;
    }
  };

  return (
    <div className="app-layout">
      <Sidebar />
      <main className="editor-main">
        {renderEditor()}
      </main>
    </div>
  );
}

function App() {
  return (
    <ScenarioProvider>
      <EditorContent />
    </ScenarioProvider>
  );
}

export default App;

// src/App.vue
<script setup lang="ts">
import { useScenarioStore } from './store/scenario'
import Sidebar from './components/Sidebar.vue'
import OverviewEditor from './components/OverviewEditor.vue'
import NPCEditor from './components/NPCEditor.vue'
import LocationEditor from './components/LocationEditor.vue'
import ClueEditor from './components/ClueEditor.vue'
import EventEditor from './components/EventEditor.vue'
import SceneEditor from './components/SceneEditor.vue'
import './App.css'

const store = useScenarioStore()
</script>

<template>
  <div class="app-layout">
    <Sidebar />
    <main class="editor-main">
      <OverviewEditor v-if="store.activeTab === 'overview'" />
      <NPCEditor v-else-if="store.activeTab === 'npc'" />
      <LocationEditor v-else-if="store.activeTab === 'location'" />
      <ClueEditor v-else-if="store.activeTab === 'clue'" />
      <EventEditor v-else-if="store.activeTab === 'event'" />
      <SceneEditor v-else-if="store.activeTab === 'scene'" />
    </main>
  </div>
</template>
